### ISSUE TITLE
themes

### ISSUE THREAD

**Issue by overtalk** [xinshangshangxin/hexo-blog#1]
你这个博客主题很好看啊
可以分享一下吗？

**Comment by xinshangshangxin** [comment]
`fork`自项目 [hexo-theme-mellow](https://github.com/codefine/hexo-theme-mellow)
博客进行部分自定义  [shang-mellow](https://github.com/xinshangshangxin/hexo-blog/tree/backup/themes/hexo-theme-mellow)
